#!/bin/bash
#######################
#    ^...^  `^...^´   #
#   / o,o \ / O,O \   #
#   |):::(| |):::(|   #
# ====" "=====" "==== #
#         TdC         #
#      1998-2022      #
#######################
# Toca das Corujas
# Códigos Binários, Funções de Onda e Teoria do Orbital Molecular Inc.
# Unidade Barão Geraldo CX
#2022_06_24_20_35_00

#############################################
#Script para substituir emotecodes por emotes

while
read -r A B;
do
sed -i "s/${A}/${B}/g" "$arquivo";
done<<EOF
:alien: 👽
:ambulance: 🚑
:angry_face: 😠
:astonished_face: 😲
:baby: 👶
:baby_bottle: 🍼
:backhand_index_pointing_left: 👈
:backhand_index_pointing_right: 👉
:balloon: 🎈
:battery: 🔋
:beaming_face_with_smiling_eyes: 😁
:beer_mug: 🍺
:bell: 🔔
:beverage_box: 🧃
:blue_heart: 💙
:bomb: 💣
:bouquet: 💐
:boxing_glove: 🥊
:boy: 👦
:brain: 🧠
:buffering: ⌛
:bus: 🚌
:call_me_hand: 🤙
:camera: 📷
:castle: 🏰
:cat_with_tears_of_joy: 😹
:chicken: 🐔
:cigarette: 🚬
:clap: 👏
:clapping_hands: 👏
:clipboard: 📋
:clown_face: 🤡
:coffin: ⚰
:cold_face: 🥶
:collision: 💥
:confused_face: 😕
:construction: 🚧
:cookie: 🍪
:cow: 🐂
:cow: 🐄
:crab: 🦀
:dashing_away: 💨
:deciduous_tree: 🌳
:disappointed_face: 😞
:disguised_face: 🥸
:dog: 🐕
:dog2: ✖️
:dog2: 🐕
:dothefive: 5️⃣
:dothefive: 5️⃣
:double_exclamation_mark: ‼
:double_exclamation_mark: ‼
:drooling_face: 🤤
:earth_africa: 🌍
:earth_americas: 🌎
:eggplant: 🍆
:elbowcough: 💪
:exclamation_question_mark: ⁉
:exploding_head: 🤯
:expressionless_face: 😑
:eye: 👁
:eyes: 👀
:face_blowing_a_kiss: 😘
:face_savoring_food: 😋
:face_screaming_in_fear: 😱
:face_vomiting: 🤮
:face_with_hand_over_mouth: 🤭
:face_with_monocle: 🧐
:face_with_open_mouth: 😮
:face_without_mouth: 😶
:face_with_raised_eyebrow: 🤨
:face_with_rolling_eyes: 🙄
:face_with_spiral_eyes: 😵‍💫
:face_with_tears_of_joy: 😂
:face_with_tongue: 😛
:fire: 🔥
:fish: 🐟
:flexed_biceps: 💪
:flushed_face: 😳
:folded_hands: 🙏
:frog: 🐸
:full_moon_face: 🌝
:garlic: 🧄
:ghost: 👻
:glass_of_milk: 🥛
:globe_showing_americas: 🌎
:globe_showing_asia_australia: 🌏
:globe_showing_europe_africa: 🌍
:goat: 🐐
:goodvibes: ✌️
:grimacing_face: 😬
:grinning_face: 😀
:grinning_face_with_big_eyes: 😃
:grinning_face_with_smiling_eyes: ✖️
:grinning_face_with_smiling_eyes: 😁
:grinning_face_with_sweat: 😅
:grinning_squinting_face: 😆
:handshake: 🤝
:hand_with_fingers_splayed: 🖐
:heart_on_fire: ❤‍🔥
:herb: 🌿
:hibiscus: 🌺
:horse: 🐎
:house_with_garden: 🏡
:hugging_face: 🤗
:hushed_face: 😯
:hydrate: 💩
:kiss: 💋
:kissing_face_with_closed_eyes: 😚
:knocked_out_face: 😵
:left_facing_fist: 🤛
:leopard: 🐆
:lollipop: 🍭
:loudly_crying_face: 😭
:loudspeaker: 📢
:lying_face: 🤥
:magnifying_glass_tilted_right: 🔎
:man_facepalming: 🤦‍♂
:man_shrugging: 🤷‍♂
:man_swimming: 🏊‍♂
:man_zombie: 🧟‍♂
:microphone: 🎤
:middle_finger: 🖕
:money_mouth_face: 🤑
:money_with_wings: 💸
:mouth: 👄
:movie_camera: 🎥
:multiply: ✖️
:musical_note: 🎵
:musical_notes: 🎶
:musical_score: 🎼
:national_park: 🏞
:nerd_face: 🤓
:neutral_face: 😐
:night_with_stars: 🌃
:office_building: 🏢
:oncoming_fist: 👊
:oops: 🤭
:oops: ✖️
:open_hands: 👐
:ox: 🐂
:partying_face: ✖️
:partying_face: 💩
:pear: 🍐
:pensive_face: 😔
:person_facepalming: 🤦
:person_fencing: 🤺
:person_gesturing_ok: 🙆
:person_raising_hand: 🙋
:person_running: 🏃
:person_shrugging: 🤷
:person_swimming: 🏊
:person_taking_bath: 🛀
:petri_dish: 🧫
:pig: 🐷
:pile_of_poo: 💩
:pill: 💊
:pizza: 🍕
:point_left: 👈
:point_right: 👉
:poodle: 🐩
:popcorn: 🍿
:potato: 🥔
:pouting_face: 😡
:prohibited: 🚫
:purple_heart: 💜
:racehorse: 🐎
:radio: 📻
:raised_fist: ✊
:raised_hand: ✋
:raising_hands: 🙌
:red_exclamation_mark: ❗
:red_heart: ❤
:red_question_mark: ❓
:relieved_face: 😌
:revolving_hearts: 💞
:right_facing_fist: 🤜
:robot: 🤖
:rolling_on_the_floor_laughing: 🤣
:rose: 🌹
:sad_but_relieved_face: 😥
:sailboat: ⛵
:scissors: ✂
:scroll: 📜
:see_no_evil_monkey: 🙈
:selfie: 🤳
:sheaf_of_rice: 🌾
:shushing_face: 🤫
:sign_of_the_horns: 🤘
:skull: 💀
:sleeping_face: 😴
:sleepy_face: 😪
:slightly_frowning_face: 🙁
:slightly_smiling_face: 🙂
:small_airplane: 🛩
:smiling_cat_with_heart_eyes: 😻
:smiling_face_with_halo: 😇
:smiling_face_with_heart_eyes: 😍
:smiling_face_with_horns: 😈
:smiling_face_with_smiling_eyes: 😊
:smiling_face_with_sunglasses: 😎
:smiling_face_with_tear: 💩
:smirking_face: 😏
:snake: 🐍
:sneezing_face: 🤧
:soccer_ball: ⚽
:socialdist: ✖️
:softball: ⚽
:sparkles: ✨
:sparkling_heart: 💖
:speaking_head: 🗣
:speak_no_evil_monkey: 🙊
:spouting_whale: 🐳
:squinting_face_with_tongue: 😝
:squinting_face_with_tongue: 😝
:star_struck: 🤩
:sun: ☀
:sweat_droplets: 💦
:syringe: 💉
:tangerine: 🍊
:test_tube: 🧪
:thermometer: 🌡
:thinking_face: 🤔
:thought_balloon: 💭
:thumbs_up: 👍
:toilet: 🚽
:triangular_ruler: 📐
:trident_emblem: 🔱
:tulip: 🌷
:turtle: 🐢
:two_hearts: 💕
:unamused_face: 😒
:upside_down_face: 🙃
:v: ✌
:victory_hand: ✌
:warning: ⚠
:washhands: 💩
:water_pistol: 🔫
:water_wave: 🌊
:waving_hand: 👋
:weary_cat: 🙀
:weary_face: 😩
:white_exclamation_mark: ❕
:winking_face: 😉
:winking_face_with_tongue: 😜
:woman_cartwheeling: 🤸‍♀️
:woman_dancing: 💃
:woman_in_lotus_position: 🧘‍♀
:woman_raising_hand: 🙋‍♀
:womans_sandal: 👡
:woozy_face: 💩
:yougotthis: 💩
:yt: ▶️
:zany_face: 🤪
:zzz: 😴
EOF
fi
